---
title: "twitterstuff"
output: html_document
date: "2022-09-17"
---

```{r, eval=T, message = F, warning=FALSE}
library(rtweet)
library(rvest)
library(xml2)
library(quanteda)
library(ggplot2)
library(tm)
```

```{r}
auth_setup_default()
```

```{r}
#collect 200 tweets using the hashtag Truss to gain knowledge of public opinion on the new British PM
liz_tweets <- search_tweets("#Truss", n = 500)
```

```{r}
truss_corpus <- iconv(liz_tweets$full_text)
truss_corpus <- Corpus(VectorSource(truss_corpus))
truss_corpus <- tm_map(truss_corpus, tolower)
inspect(truss_corpus[1:5])
```

```{r}
cleantruss <- tm_map(truss_corpus, removeWords, stopwords('english'))
cleantruss <- tm_map(truss_corpus, removeWords, c("the", "and", "has", "that", "her", "she", "have", "will", "for", "are", "they", "from", "this", "was", "with"))
cleantruss <- tm_map(cleantruss, stemDocument)
cleantruss <- tm_map(cleantruss, stripWhitespace)
```

```{r}
tdmtruss <- TermDocumentMatrix(cleantruss)
tdmtruss <- as.matrix(tdmtruss)
tdmtruss[1:10, 1:20]
```

```{r}
library(wordcloud)
```

```{r}
w <- sort(rowSums(tdmtruss), decreasing = TRUE)
set.seed(222)
wordcloud(words = names(w),
          freq = w,
          max.words = 150,
          random.order = F,
          min.freq = 5,
          colors = brewer.pal(8, 'Dark2'),
          scale = c(5, 0.3),
          rot.per = 0.7)
w
```
